### ISSUE TITLE
can i plugin this library with java gstreamer

### ISSUE THREAD

**Issue by badboys4life007** [alumae/gst-kaldi-nnet2-online#17]
Hello,

i used your python code as reference and code in java using gstreamer-java-1.6.jar and jna-4.1.0.jar but there it cannot load kaldi gstreamer library and says error as No such Gstreamer factory: kaldinnet2onlinedecoder

i even set the library path but does this library would load using gstreamer-java-1.6.jar.

Please suggest me what to do, it will be very helpful to me.

**Comment by alumae** [comment]
It should work with Java although I haven't really tried.

The error message seems to indicate that GStreamer doesn't find the library that contains kaldinnet2onlinedecoder. Have you set the GST_PLUGIN_PATH environment variable to point to the directory that contains the plugin? E.g., can you run `GST_PLUGIN_PATH=/home/foo/gst-kaldi-nnet2-online/src gst-inspect-1.0 kaldinnet2onlinedecoder` from the same directory where you execute you Java program?

**Comment by badboys4life007** [comment]
yes i tried all the possibilities and after all finally, i come to know
that GStreamer Java has only supporting version of GStreamer 0.10 (here is
refer url https://code.google.com/p/gstreamer-java/) and it has no
supported version for *GStreamer 1.0 or above* in java.

and i think we cant compile kaldi code with GStreamer 0.10 as i even tried
to do it even but failed.

**Comment by alumae** [comment]
Yes, the plugin doesn't support GStreamer 0.10, sorry.

**Comment by badboys4life007** [comment]
okey thanks for the response. so i suppose to work with python wrapper for
GUI..

thanks, your effort saved my time..

**Comment by gilamsalem** [comment]
I just found this thread while searching for a Java kaldi gstreamer plugin. 
Anyway, in case it is relevant to someone, I am using org.freedesktop.gstreamer package, and it works fine with the gst-kaldi-nnet2-online plugin.

**Comment by justinphan3110** [comment]
Hi @gilamsalem, thanks for the update. Can you share the code implementing org.freedesktop.gstreamer package with the  gst-kaldi-nnet2-online plugin also?

**Comment by gilamsalem** [comment]
Hi @justinphan3110 
I haven't touched it for a long long time...
I attached the files I found, hope it is still working:
[gstreamerjava.zip](https://github.com/alumae/gst-kaldi-nnet2-online/files/5378833/gstreamerjava.zip)

**Comment by gilamsalem** [comment]
I think that the relevant gstreamer version is:
`        
<groupId>org.freedesktop.gstreamer</groupId>
<artifactId>gst1-java-core</artifactId>
<version>0.9.4</version>
`

**Comment by justinphan3110** [comment]
@gilamsalem thank you for the sharing! Your code would great to be one of a example for the [gst1-java-examples](https://github.com/gstreamer-java/gst1-java-examplesl) also

**Comment by gilamsalem** [comment]
@justinphan3110 Cool.
I will follow.
Ping me if I can help more...
