### ISSUE TITLE
won't compile now

### ISSUE THREAD

**Issue by cchiwei** [alumae/gst-kaldi-nnet2-online#21]
Hello, can you help to resolve the error I am having

chiweic@chiweic-VirtualBox:~/gst-kaldi-nnet2-online/src$ KALDI=/home/chiweic/kaldi-trunk make
g++ -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/chiweic/kaldi-trunk/tools/ATLAS/include -I/home/chiweic/kaldi-trunk/tools/openfst/include -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -g  -fPIC -I/home/chiweic/kaldi-trunk/src   -c -o gstkaldinnet2onlinedecoder.o gstkaldinnet2onlinedecoder.cc
gstkaldinnet2onlinedecoder.cc: In function ‘std::string kaldi::gst_kaldinnet2onlinedecoder_full_final_result_to_json(kaldi::Gstkaldinnet2onlinedecoder*, const FullFinalResult&)’:
gstkaldinnet2onlinedecoder.cc:1032:61: error: ‘JSON_REAL_PRECISION’ was not declared in this scope
   char *ret_strings = json_dumps(root, JSON_REAL_PRECISION(6));
                                                             ^
In file included from /home/chiweic/kaldi-trunk/src/base/kaldi-common.h:38:0,
                 from /home/chiweic/kaldi-trunk/src/util/simple-options.h:27,
                 from ././simple-options-gst.h:25,
                 from ./gstkaldinnet2onlinedecoder.h:26,
                 from gstkaldinnet2onlinedecoder.cc:49:
/home/chiweic/kaldi-trunk/src/base/kaldi-math.h: At global scope:
/home/chiweic/kaldi-trunk/src/base/kaldi-math.h:86:17: warning: ‘kaldi::kLogZeroBaseFloat’ defined but not used [-Wunused-variable]
 const BaseFloat kLogZeroBaseFloat = -std::numeric_limits<BaseFloat>::infinity();
                 ^
make: *** [gstkaldinnet2onlinedecoder.o] Error 1

**Comment by alumae** [comment]
You need to install the Jansson library together with its development header files (version 2.7 or later). This does this on Debian:

    sudo apt-get install libjansson-dev

**Comment by kdavis-mozilla** [comment]
On Ubuntu Server 14.04 this doesn't seem to do the trick:
```
ubuntu@ip-172-31-28-188:~/kaldi/tools/gst-kaldi-nnet2-online/src$ sudo apt-get install libjansson-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjansson-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 110 not upgraded.
ubuntu@ip-172-31-28-188:~/kaldi/tools/gst-kaldi-nnet2-online/src$ KALDI_ROOT=/home/ubuntu/kaldi make
g++ -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/ubuntu/kaldi/tools/ATLAS/include -I/home/ubuntu/kaldi/tools/openfst/include -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -g  -fPIC -I/home/ubuntu/kaldi/src   -c -o gstkaldinnet2onlinedecoder.o gstkaldinnet2onlinedecoder.cc
gstkaldinnet2onlinedecoder.cc: In function 'std::string kaldi::gst_kaldinnet2onlinedecoder_full_final_result_to_json(kaldi::Gstkaldinnet2onlinedecoder*, const FullFinalResult&)':
gstkaldinnet2onlinedecoder.cc:1055:61: error: 'JSON_REAL_PRECISION' was not declared in this scope
   char *ret_strings = json_dumps(root, JSON_REAL_PRECISION(6));
                                                             ^
In file included from /home/ubuntu/kaldi/src/base/kaldi-common.h:38:0,
                 from /home/ubuntu/kaldi/src/util/simple-options.h:27,
                 from ././simple-options-gst.h:25,
                 from ./gstkaldinnet2onlinedecoder.h:26,
                 from gstkaldinnet2onlinedecoder.cc:49:
/home/ubuntu/kaldi/src/base/kaldi-math.h: At global scope:
/home/ubuntu/kaldi/src/base/kaldi-math.h:126:17: warning: 'kaldi::kLogZeroBaseFloat' defined but not used [-Wunused-variable]
 const BaseFloat kLogZeroBaseFloat = -std::numeric_limits<BaseFloat>::infinity();
                 ^
make: *** [gstkaldinnet2onlinedecoder.o] Error 1
```

**Comment by kdavis-mozilla** [comment]
I think the trick is JSON_REAL_PRECISION is new in version 2.7. Using
the command
```
sudo apt-get install libjansson-dev
```
Ubuntu Server 14.04 installs 2.5-2

**Comment by crazydreamer** [comment]
hello, I run into same problem here, I already install  libjansson-dev  by " sudo apt-get install libjansson-dev"  on  ubuntu 14.04,  my python version is 2.7.6 do you have any suggestion ?

**Comment by alumae** [comment]
What is the version of libjansson-dev? It has nothing to do with the python version.

**Comment by geffy** [comment]
Same problem, libjansson-dev 2.5-2

**Comment by alumae** [comment]
You need libjansson 2.7.

**Comment by cchiwei** [comment]
try GitHub the libjansson with the correct or above version, recompile and set the folder the installation.

**Comment by geffy** [comment]
Yes, it helps for me. Thanks!
