### ISSUE TITLE
g_new()/g_free() is different from new/delete

### ISSUE THREAD

**Issue by wegylexy** [alumae/gst-kaldi-nnet2-online#25]
`g_value_dup_string()` calls `g_new()` which in turn calls `malloc()` internally, so it should be `g_free()` rather than `operator delete()` to release `adaptation_state_string` on line 667 of gstkaldinnet2onlinedecoder.cc

while it seems to work fine on Linux, Visual C++ Runtime caught heap corruption on Windows

please change `delete adaptation_state_string;` to `g_free(adaptation_state_string);`

**Comment by alumae** [comment]
Thanks a lot for noticing this! Can you make a pull request?

**Comment by wegylexy** [comment]
I'm new to GitHub. The "Create pull request" button is greyed out. How do I create a pull request?

**Comment by wegylexy** [comment]
okay, I didn't know I have to fork it before I can create a pull request.
