### ISSUE TITLE
Plugin compile error

### ISSUE THREAD

**Issue by lucgeo** [alumae/gst-kaldi-nnet2-online#27]
Hi, 

I followed the installation steps and I got an error when I want to compile specifying Kaldi's root directory.
command: "make depend KALDI_ROOT=/home/kaldi-trunk make".
error: g++ -M -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/georgescu/kaldi-trunk/tools/ATLAS/include -I/home/georgescu/kaldi-trunk/tools/openfst/include -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -g  -fPIC -DHAVE_CUDA -I/usr/local/cuda/include  -DKALDI_NO_EXPF -I/home/georgescu/kaldi-trunk/src *.cc > .depend.mk  
make: *** No rule to make target `make'.  Stop.

How to solve it?

Thanks.

**Comment by alumae** [comment]
'make depend' and 'KALDI_ROOT=/path/of/kaldi-trunk make' should be separate commands.
