### ISSUE TITLE
KALDI_ROOT=/path/of/kaldi-trunk make issue

### ISSUE THREAD

**Issue by lucgeo** [alumae/gst-kaldi-nnet2-online#28]
Hi, 

Thanks for your previous answer. I still have a problem when I run "KALDI_ROOT=/path/of/kaldi-trunk make". This is the output:

In file included from gstkaldinnet2onlinedecoder.cc:49:0:
./gstkaldinnet2onlinedecoder.h:84:3: error: ‘OnlineSilenceWeightingConfig’ does not name a type
   OnlineSilenceWeightingConfig *silence_weighting_config;
   ^
gstkaldinnet2onlinedecoder.cc: In function ‘void kaldi::gst_kaldinnet2onlinedecoder_init(kaldi::Gstkaldinnet2onlinedecoder*)’:
gstkaldinnet2onlinedecoder.cc:478:11: error: ‘kaldi::Gstkaldinnet2onlinedecoder’ has no member named ‘silence_weighting_config’
   filter->silence_weighting_config = new OnlineSilenceWeightingConfig();
           ^
gstkaldinnet2onlinedecoder.cc:478:42: error: expected type-specifier before ‘OnlineSilenceWeightingConfig’
   filter->silence_weighting_config = new OnlineSilenceWeightingConfig();
                                          ^
gstkaldinnet2onlinedecoder.cc:478:42: error: expected ‘;’ before ‘OnlineSilenceWeightingConfig’
gstkaldinnet2onlinedecoder.cc:482:11: error: ‘kaldi::Gstkaldinnet2onlinedecoder’ has no member named ‘silence_weighting_config’
   filter->silence_weighting_config->Register(filter->simple_options);
           ^
gstkaldinnet2onlinedecoder.cc: In function ‘std::string kaldi::gst_kaldinnet2onlinedecoder_full_final_result_to_json(kaldi::Gstkaldinnet2onlinedecoder*, const FullFinalResult&)’:
gstkaldinnet2onlinedecoder.cc:994:70: error: ‘json_boolean’ was not declared in this scope
   json_object_set_new( result_json_object, "final", json_boolean(true));
                                                                      ^
gstkaldinnet2onlinedecoder.cc:1055:61: error: ‘JSON_REAL_PRECISION’ was not declared in this scope
   char *ret_strings = json_dumps(root, JSON_REAL_PRECISION(6));
                                                             ^
In file included from /usr/include/gstreamer-1.0/gst/gst.h:50:0,
                 from gstkaldinnet2onlinedecoder.cc:46:
gstkaldinnet2onlinedecoder.cc: In function ‘void kaldi::gst_kaldinnet2onlinedecoder_threaded_decode_segment(kaldi::Gstkaldinnet2onlinedecoder*, bool&, kaldi::int32, kaldi::BaseFloat, kaldi::Vector<float>*)’:
gstkaldinnet2onlinedecoder.cc:1213:34: error: ‘class kaldi::SingleUtteranceNnet2DecoderThreaded’ has no member named ‘NumWaveformPiecesPending’
                          decoder.NumWaveformPiecesPending());
                                  ^
/usr/include/gstreamer-1.0/gst/gstinfo.h:525:31: note: in definition of macro ‘GST_CAT_LEVEL_LOG’
         (GObject *) (object), __VA_ARGS__);    \
                               ^
gstkaldinnet2onlinedecoder.cc:1210:9: note: in expansion of macro ‘GST_DEBUG_OBJECT’
         GST_DEBUG_OBJECT(filter, "Before the sleep check: Frames received: ~ %d, frames decoded: %d, pieces pending: %d",
         ^
gstkaldinnet2onlinedecoder.cc:1224:34: error: ‘class kaldi::SingleUtteranceNnet2DecoderThreaded’ has no member named ‘NumWaveformPiecesPending’
                          decoder.NumWaveformPiecesPending());
                                  ^
/usr/include/gstreamer-1.0/gst/gstinfo.h:525:31: note: in definition of macro ‘GST_CAT_LEVEL_LOG’
         (GObject *) (object), __VA_ARGS__);    \
                               ^
gstkaldinnet2onlinedecoder.cc:1221:9: note: in expansion of macro ‘GST_DEBUG_OBJECT’
         GST_DEBUG_OBJECT(filter, "After the sleep check: Frames received: ~ %d, frames decoded: %d, pieces pending: %d",
         ^
gstkaldinnet2onlinedecoder.cc:1245:13: error: ‘class kaldi::SingleUtteranceNnet2DecoderThreaded’ has no member named ‘GetRemainingWaveform’
     decoder.GetRemainingWaveform(remaining_wave_part);
             ^
gstkaldinnet2onlinedecoder.cc: In function ‘void kaldi::gst_kaldinnet2onlinedecoder_unthreaded_decode_segment(kaldi::Gstkaldinnet2onlinedecoder*, bool&, kaldi::int32, kaldi::BaseFloat)’:
gstkaldinnet2onlinedecoder.cc:1287:3: error: ‘OnlineSilenceWeighting’ was not declared in this scope
   OnlineSilenceWeighting silence_weighting(*(filter->trans_model),
   ^
gstkaldinnet2onlinedecoder.cc:1287:26: error: expected ‘;’ before ‘silence_weighting’
   OnlineSilenceWeighting silence_weighting(*(filter->trans_model),
                          ^
gstkaldinnet2onlinedecoder.cc:1304:9: error: ‘silence_weighting’ was not declared in this scope
     if (silence_weighting.Active()) {
         ^
gstkaldinnet2onlinedecoder.cc:1305:57: error: ‘class kaldi::SingleUtteranceNnet2Decoder’ has no member named ‘Decoder’
       silence_weighting.ComputeCurrentTraceback(decoder.Decoder());
                                                         ^
gstkaldinnet2onlinedecoder.cc:1307:24: error: ‘class kaldi::OnlineNnet2FeaturePipeline’ has no member named ‘UpdateFrameWeights’
       feature_pipeline.UpdateFrameWeights(delta_weights);
                        ^
gstkaldinnet2onlinedecoder.cc: In function ‘void kaldi::gst_kaldinnet2onlinedecoder_finalize(GObject*)’:
gstkaldinnet2onlinedecoder.cc:1868:18: error: ‘kaldi::Gstkaldinnet2onlinedecoder’ has no member named ‘silence_weighting_config’
   delete filter->silence_weighting_config;
                  ^
In file included from /home/georgescu/kaldi-trunk//src/base/kaldi-common.h:38:0,
                 from /home/georgescu/kaldi-trunk//src/util/simple-options.h:27,
                 from ././simple-options-gst.h:25,
                 from ./gstkaldinnet2onlinedecoder.h:26,
                 from gstkaldinnet2onlinedecoder.cc:49:
/home/georgescu/kaldi-trunk//src/base/kaldi-math.h: At global scope:
/home/georgescu/kaldi-trunk//src/base/kaldi-math.h:86:17: warning: ‘kaldi::kLogZeroBaseFloat’ defined but not used [-Wunused-variable]
 const BaseFloat kLogZeroBaseFloat = -std::numeric_limits<BaseFloat>::infinity();
                 ^
make: *** [gstkaldinnet2onlinedecoder.o] Error 1

Thanks for help.

**Comment by alumae** [comment]
Ar you sure you are using the latest Kaldi from github?

**Comment by lucgeo** [comment]
Hi,

I just installed the latest version of Kaldi. This is the error that I got:

georgescu@zeta:~/gst-kaldi/src$ KALDI_ROOT=~/kaldi-trunk make
g++ -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/georgescu/kaldi-trunk/tools/ATLAS/include -I/home/georgescu/kaldi-trunk/tools/openfst/include -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -g  -fPIC -DHAVE_CUDA -I/usr/local/cuda/include  -DKALDI_NO_EXPF -I/home/georgescu/kaldi-trunk/src   -c -o gstkaldinnet2onlinedecoder.o gstkaldinnet2onlinedecoder.cc
gstkaldinnet2onlinedecoder.cc: In function ‘std::string kaldi::gst_kaldinnet2onlinedecoder_full_final_result_to_json(kaldi::Gstkaldinnet2onlinedecoder*, const FullFinalResult&)’:
gstkaldinnet2onlinedecoder.cc:994:70: error: ‘json_boolean’ was not declared in this scope
   json_object_set_new( result_json_object, "final", json_boolean(true));
                                                                      ^
gstkaldinnet2onlinedecoder.cc:1055:61: error: ‘JSON_REAL_PRECISION’ was not declared in this scope
   char *ret_strings = json_dumps(root, JSON_REAL_PRECISION(6));
                                                             ^
In file included from /home/georgescu/kaldi-trunk/src/base/kaldi-common.h:38:0,
                 from /home/georgescu/kaldi-trunk/src/util/simple-options.h:27,
                 from ././simple-options-gst.h:25,
                 from ./gstkaldinnet2onlinedecoder.h:26,
                 from gstkaldinnet2onlinedecoder.cc:49:
/home/georgescu/kaldi-trunk/src/base/kaldi-math.h: At global scope:
/home/georgescu/kaldi-trunk/src/base/kaldi-math.h:126:17: warning: ‘kaldi::kLogZeroBaseFloat’ defined but not used [-Wunused-variable]
 const BaseFloat kLogZeroBaseFloat = -std::numeric_limits<BaseFloat>::infinity();
                 ^
make: *** [gstkaldinnet2onlinedecoder.o] Error 1

Any idea about what is wrong?

Thanks.

**Comment by alumae** [comment]
You need libjansson 2.7 or newer.
