### ISSUE TITLE
Ubuntu 12.04; ReadDecodeGraph

### ISSUE THREAD

**Issue by ryryguy** [alumae/gst-kaldi-nnet2-online#29]
Hi,

I've been playing with this plugin, which is pretty great. 

I'm running with Ubuntu 12.04 (Precise) and there are a couple of little compatibility issues. First is that to get gstreamer 1.0, you have to use a backport ppa, like so:

    sudo add-apt-repository ppa:gstreamer-developers/ppa
    sudo apt-get update
    sudo apt-get install gstreamer1.0-plugins-bad  gstreamer1.0-plugins-base gstreamer1.0-plugins-good  gstreamer1.0-pulseaudio  gstreamer1.0-plugins-ugly  gstreamer1.0-tools libgstreamer1.0-dev

Next, the version of lib-jansson that is available for Ubuntu 12.04 is 2.2.1-1. It seems to be compatible for the most part, but I had to make two minor changes for macros that aren't present in the older version (see below).

Finally, we are using a "const" fst instead of the vector style, so I changed ReadFstKaldi to ReadDecodeGraph. ReadDecodeGraph will handle either style of fst, so there doesn't seem to be any reason not to use it in the plugin

See diff below... if you'd like me to submit a pull request I'd be happy to do so. 

```
--- a/src/gstkaldinnet2onlinedecoder.cc
+++ b/src/gstkaldinnet2onlinedecoder.cc
@@ -58,6 +58,11 @@
 
 #include <jansson.h>
 
+/* JSON_REAL_PRECISION is a macro from libjansson 2.7. Ubuntu 12.04 only has 2.2.1-1 */
+#ifndef JSON_REAL_PRECISION
+#define JSON_REAL_PRECISION(n)  (((n) & 0x1F) << 11)
+#endif // JSON_REAL_PRECISION
+
 
 namespace kaldi {
 
@@ -991,7 +996,7 @@ static std::string gst_kaldinnet2onlinedecoder_full_final_result_to_json(
 
   json_object_set_new( root, "result", result_json_object);
 
-  json_object_set_new( result_json_object, "final", json_boolean(true));
+  json_object_set_new( result_json_object, "final", json_true());
 
   if (full_final_result.nbest_results.size() > 0) {
     BaseFloat frame_shift = filter->feature_info->FrameShiftInSeconds();
@@ -1664,7 +1669,7 @@ gst_kaldinnet2onlinedecoder_load_fst(Gstkaldinnet2onlinedecoder * filter,
       try {
         GST_DEBUG_OBJECT(filter, "Loading decoder graph: %s", str);
 
-        fst::Fst<fst::StdArc> * new_decode_fst = fst::ReadFstKaldi(str);
+        fst::Fst<fst::StdArc> * new_decode_fst = ReadDecodeGraph(str);
 
         // Delete objects if needed
         if (filter->decode_fst) {
```

**Comment by alumae** [comment]
It looks good. Please make a pull request. Thanks a lot!
