### ISSUE TITLE
read full-final-result

### ISSUE THREAD

**Issue by MatteoBotta** [alumae/gst-kaldi-nnet2-online#35]
Hi,
I try to transcribe with script "transcribe-audio.sh" and system shows correctly normal transcription.
Now I would generate  a text transcription with full-final-result.
I set transcribe-audio.sh with these parameters: 

GST_PLUGIN_PATH=../src gst-launch-1.0 --gst-debug="" -q filesrc location=$audio ! decodebin ! audioconvert ! audioresample ! \
kaldinnet2onlinedecoder \
  use-threaded-decoder=true \
  model=final.mdl \
  fst=HCLG.fst \
  word-syms=words.txt \
  feature-type=mfcc \
  mfcc-config=conf/mfcc.conf \
  ivector-extraction-config=conf/ivector_extractor.fixed.conf \
  max-active=7000 \
  beam=11.0 \
  lattice-beam=5.0 \
  do-endpointing=true \
  do-phone-alignment=true \
  num-nbest=10 \
  endpoint-silence-phones="1:2:3:4:5:6:7:8:9:10" \
  chunk-length-in-secs=0.2 \
! filesink location=/dev/stdout buffer-mode=2

but system shows always normal text transcription without word time information.

Could you help me?

Thank in Advance

Mat

**Comment by alumae** [comment]
You cannot get the full results from the command line (as far as I know). This is because the full results are pushed out via a signal, not via the components output pad.

**Comment by MatteoBotta** [comment]
Thanks.
Now I use a python script to generate full result

Best Regards
Matteo

**Comment by heqiqi** [comment]
@MatteoBotta 
Hi MatteoBotta, 
I am trying to generate full result too. Could you share your script? I am  not familiar with  python?

**Comment by YichiHuang** [comment]
I am also trying to generate full result but I have no idea. Can you give me same comments? Thanks. @MatteoBotta
