### ISSUE TITLE
Timing offset for segments

### ISSUE THREAD

**Issue by alumae** [alumae/gst-kaldi-nnet2-online#37]
A user reported: I'm obtaining word timing alignments, but the end of each sequence introduces a sporadic timing offset. i.e. after the 1st sequence, the 2nd sequence is misaligned by around 0.5 seconds, which increases from the 2nd to 3rd, 3rd to 4th, etc.

**Comment by alumae** [comment]
Yes, please send everything that is needed to reproduce it to alumae@gmail.com

**Comment by antho-rousseau** [comment]
Thanks Tanel, I've finally sorted the issue by playing with the plugin parameters. Using `frames-per-chunk=140 chunk-length-in-secs=0.2` did the trick, no more offsets for me.
