### ISSUE TITLE
nnet3 / chain

### ISSUE THREAD

**Issue by vince62s** [alumae/gst-kaldi-nnet2-online#39]
Hi,

Would that take much effort to make this compatible with nnet3 or tdnn chain models ?

can you please point out the places that need modification in the C code ?

cheers,

**Comment by alumae** [comment]
I plan to do it sometime later this year. It requires a lot of work, I cannot just point out the paces

**Comment by yifan** [comment]
I have made some modification to support nnet3 model, there are WIP because I haven't verified the recognition result. Please let me know if this is going to work, @alumae Thank you.
https://github.com/alumae/kaldi-gstreamer-server/pull/52
https://github.com/alumae/gst-kaldi-nnet2-online/pull/41

**Comment by alumae** [comment]
Thank you @yifan! I merged your code, seems to work well. Didn't test very carefully.
