### ISSUE TITLE
using gpu for online decoding

### ISSUE THREAD

**Issue by aditya6992** [alumae/gst-kaldi-nnet2-online#40]
it looks like online decoding using gpu hasnt been implemented, is this intentional?

**Comment by alumae** [comment]
Yes

**Comment by tlc** [comment]
Is this still true?  Is doing so impractical or unlikely to improve performance?  Or just not interesting to the developers?

**Comment by alumae** [comment]
I don't really see much practicality in it. Decoding using a CPU using chain models is anyway faster than realtime. Decoding using a GPU would be even faster, but then you would one GPU per worker, which is expensive.
