### ISSUE TITLE
plugin works in standalone test not in server

### ISSUE THREAD

**Issue by yifan** [alumae/gst-kaldi-nnet2-online#43]
@alumae I need some help on debugging an issue I have with my changes. The plugin works if I run it with gstlaunch in command line but not as worker in server. the main problem is that it doesn't produce any partial result (always get "" as partial results if I check in the DEBUG log). At first I thought it was because that the nnet-mode wasn't set at the beginning, some decoding parameter wasn't set correctly. I fixed that and the problem still occurs. I am thinking you may have some insight what may be the cause of the problem. Thanks.

**Comment by yifan** [comment]
mmm.. Looks like I am getting all zeros for the audio. Maybe something wrong with my browser maybe. Very strange. I managed to get data feed into recognize with client.py though.

**Comment by alumae** [comment]
Hi, I am very busy with other stuff until the end of September but after that I have a lot of time to work on that. I hope you can make it until then.

**Comment by yifan** [comment]
it was due to my browser problem. It is working fine now.
