### ISSUE TITLE
nnet3 "Chain" model

### ISSUE THREAD

**Issue by vince62s** [alumae/gst-kaldi-nnet2-online#45]
Hi,
I installed successfully everything as in the doc.
NNet2 with tedlium model from the example works fine as expected for the bill gates mp3 file.

I tried a nnet3 chain model.
it works with the wav english_test.wav 
it does not work with the bill gates mp3 file.
it spits out "whoa." and that's it.

can you confirm that we need:
use-nnet2: True
and first property in decoder
nnet-mode: 3

any clue ?

**Comment by vince62s** [comment]
@yifan did it work for the Bill gates mp3 file with a chain configuration ?

**Comment by vince62s** [comment]
I think I know why.
For Chain models the acoustic scale / language scale is different.
we need to replicate these option at decoding time
--acwt 1.0 --post-decode-acwt 10.0
so we can make the acoustic scale 1.0 instead of defaut 0.083 but we need another property I guess
for post decode scale.

**Comment by yifan** [comment]
@vince62 Yes, you have to set **acoustic-scale** to be 1.0. Also  I have set frame-subsampling-factor to be 3. Other than that, the only thing for my model is that **lmwt-scale** has to be 1.0 (default value) as well. Any other value will produce worse result than the default value (1.0). Also threaded decoder doesn't really work here, **use-threaded-decoder:false**.

**Comment by vince62s** [comment]
Thanks yifan.
What do you mean by "lmwt-scale" has to be 1.0 ? is this a decoder property too ?
where would we replicate the post-decode-acwt, which is in the LM scale being close to 10 ?

**Comment by alumae** [comment]
The post-decode-acwt in Kaldi is only used for scaling the acoustic scores in the output lattices. Since we don't output any lattices, I don't think we need it.

**Comment by yifan** [comment]
@vince62s that's a decoder property. The default value is 1.0 if you don't set it. It is the language model weight when extracting best path from the final lattice. In theory, it should be the same as best LMWT in your experiment.

**Comment by vince62s** [comment]
hmm. I am not sure. I have the feeling it works best with lmwt-scale=1.0
But then I don't see any point where I set 9 or 10 [this number being my best LMWT in my experiment]

unrelated, but do you use dictate.js as well ? I tried to set it up, but its very unstable for both Firefox and Chrome (last versions).

**Comment by yifan** [comment]
@vince62s yes, I do use dictate.js in one of my project. It has been working fine. What exactly do you mean by unstable?

**Comment by alumae** [comment]
BTW, remember to also set `frame-subsampling-factor: 3` if you use chain models. This property is not exposed when you do `gst-inspect-1.0 kaldinnet2onlinedecoder` because the nnet3 properties are kind of hidden, I don't know how to fix this...

**Comment by yifan** [comment]
@alumae it is exposed when you do gst-inspect.
```
  max-nnet-batch-size : Maximum batch size we use in neural-network decodable object, in cases where we are not constrained by currently available frames (this will rarely make a difference)
                        flags: readable, writable
                        Integer. Range: -2147483648 - 2147483647 Default: 256
  frame-subsampling-factor: Required if the frame-rate of the output (e.g. in 'chain' models) is less than the frame-rate of the original alignment.
                        flags: readable, writable
                        Integer. Range: -2147483648 - 2147483647 Default: 1
  optimization-optimize: Set this to false to turn off all optimizations
                        flags: readable, writable
                        Boolean. Default: true
```

**Comment by alumae** [comment]
You are right, it's exposed. I was using an outdated plugin.

**Comment by russlevy** [comment]
This seems to work for me, probably can be closed.

**Comment by maelp** [comment]
Hi, I saw this issue and am wondering if there is a reason why chain models could not be threaded?

**Comment by alumae** [comment]
The main reason is that the threaded decding is not implemented for nnet3 in Kaldi. Also, there is little point in doing threaded decoding for chain models since it's very easy to get faster than realtime speed with chain models.

**Comment by anchalrani** [comment]
Please may I know where are we supposed to make these changes 
frame-subsampling-factor:3
nnet-mode: 3
