### ISSUE TITLE
make error because of nnet3

### ISSUE THREAD

**Issue by HyuksuRyu** [alumae/gst-kaldi-nnet2-online#48]
I have recently compiled kaldi (up-to-date) succefully. (Ubuntu server 16.04)
Now I am trying to compile gst-kaldi-nnet2-online. 
I downloaded gst-kaldi-nnet2-online through github and completed until make depend. 
However, When I try 
`$ KALDI_ROOT=/media/data2/kaldi-ryu make` 
`/media/data2/kaldi-ryu` is the path where kaldi is complied (`/media/data2/kaldi-ryu/src`).

I got error message as below
`g++ -std=c++11 -I.. -I/media/data2/kaldi-ryu/tools/openfst/include -pthread -I/usr/include/gstreamer-1.0 -I/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/media/data2/kaldi-ryu/tools/ATLAS/include -msse -msse2 -pthread -g  -fPIC -DHAVE_CUDA -I/usr/local/cuda/include -DHAVE_SPEEX -I/media/data2/kaldi-ryu/src/../tools/speex/include -I/media/data2/kaldi-ryu/src   -c -o gstkaldinnet2onlinedecoder.o gstkaldinnet2onlinedecoder.cc
In file included from ./gstkaldinnet2onlinedecoder.h:33:0,
                 from gstkaldinnet2onlinedecoder.cc:50:
/media/data2/kaldi-ryu/src/online2/online-nnet3-decoding.h:54:10: error: ‘DecodableNnet3OnlineOptions’ in namespace ‘kaldi::nnet3’ does not name a type
   nnet3::DecodableNnet3OnlineOptions decodable_opts;
          ^
/media/data2/kaldi-ryu/src/online2/online-nnet3-decoding.h: In constructor ‘kaldi::OnlineNnet3DecodingConfig::OnlineNnet3DecodingConfig()’:
/media/data2/kaldi-ryu/src/online2/online-nnet3-decoding.h:56:34: error: ‘decodable_opts’ was not declared in this scope
   OnlineNnet3DecodingConfig() {  decodable_opts.acoustic_scale = 0.1; }`

When I checked `$KALDI_ROOT/src/online2/online-nnet3-decoding.h`, I found that the header file does not declare the type `DecodableNnet3OnlineOption`, while the type `DecodableNnet2OnlineOption` is declared in `$KALDI_ROOT/src/online2/online-nnet2-decoding.h`.

So, I modify `online-nnet3-decoding.h` by putting the declaration of the type `DecodableNnet3OnlineOption` like in `online-nnet2-decoding.h`, where I just substitute Nnet2 to Nnet3. 

But I still have error. 

What can I do to fix it?

**Comment by okokookokok** [comment]
Both `online-nnet3-decoding.h` and `online-nnet3-decoding.cc` were both changed quite a bit in Kaldi 5.1 and `gst-kaldi-nnet2-online` will require some rewriting to support it.

**Comment by alumae** [comment]
Oh, I didn't know that. I will work on this ASAP.

**Comment by alumae** [comment]
Should be fixed.
