### ISSUE TITLE
Online Program Kaldi

### ISSUE THREAD

**Issue by aliudinwijaya** [alumae/gst-kaldi-nnet2-online#49]
When try in code : 
\verbatim
gst-launch-1.0 -q alsasrc  \
    ! decodebin ! audioconvert ! audioresample \
    ! onlinegmmdecodefaster model=tri2b_mmi/model fst=tri2b_mmi/HCLG.fst \
                            word-syms=tri2b_mmi/words.txt silence-phones="1:2:3:4:5" lda-mat=tri2b_mmi/matrix \
    ! filesink location=/dev/stdout buffer-mode=2
\endverbatim

Stream = OK and running.

but I want to release the results of the transcript and audio wav form, I was confused to add Which section of it, please help her, thanks

**Comment by alumae** [comment]
If you want to transcribe a file, replace 'alsasrc' with 'filesrc location=/path/to/file.wav' . Other file formats (mp3, ogg) should also work like that, if you have the required GStreamer plugins installed.

**Comment by aliudinwijaya** [comment]
sorry, if I want to stream using a microphone, and I wanted to pull out (echo) the results of stream chunks wav audio form, and transcription.

the location where should I add?

sorry, can you for example, using a bash script, thanks.

Best regards

**Comment by aliudinwijaya** [comment]
I've tried it :
gst-launch-1.0 -q pulsesrc  \
    ! decodebin ! audioconvert ! audioresample \
    ! audiocheblimit mode=high-pass cutoff=150 ! audioconvert \
    ! onlinegmmdecodefaster model=/root/final.mdl fst=/root/HCLG.fst \
                            word-syms=/root/words.txt silence-phones="1:2:3:4:5:6:7:8:9:10:11:12:13:14:15" \
			    cmn-window=1600 \
    ! filesink location=/dev/stdout buffer-mode=2 | tee -a demo.txt

but I am confused as to add, can help me?
Best regards

**Comment by alumae** [comment]
Sorry for the delayed answer.
I think what you want is possible. You have to split the audio stream to two parallel copies, using the tee element, if I remember correctly. And you have to use queue elements after tee, to prevent deadlocking. I tried once something like this, but have forgotten about this. See for example: http://gstreamer-devel.966125.n4.nabble.com/Good-example-to-show-usage-of-tee-td4656821.html
