### ISSUE TITLE
make depend issue

### ISSUE THREAD

**Issue by j0sborne** [alumae/gst-kaldi-nnet2-online#52]
So when I run "make depend" before KALDI_ROOT I get this statement.

"/Documents/yunks/kaldi/src/src$ make depend
Makefile:6: *** Cannot find Kaldi's makefile /home/tanel/tools/kaldi-trunk/src/kaldi.mk. Specify Kaldi's root directory using KALDI_ROOT when issuing make, e.g.: `KALDI_ROOT=/home/tanel/tools/kaldi-trunk make` .  Stop."

Should I be running make depend and KALDI_ROOT as one command? 
I'm in the source folder I get from github when i try make depend.  Everything before this step worked just fine. Please help.

**Comment by alumae** [comment]
Yes, it should be one command, e.g.:
` KALDI_ROOT=/home/tanel/tools/kaldi-trunk make depend`
