### ISSUE TITLE
command-line demo issue

### ISSUE THREAD

**Issue by j0sborne** [alumae/gst-kaldi-nnet2-online#53]
When I try to run "./transcribe-audio.sh dr_strangelove.mp3" I get the follow to happen.

LOG ([5.2]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG ([5.2]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
huh i hello this is hello dimitri listen i i can't hear too well do you support you could turn the music down just a little
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
./transcribe-audio.sh: line 33: 65040 Aborted                 (core dumped) GST_PLUGIN_PATH=../src gst-launch-1.0 --gst-debug="" -q filesrc location=$audio ! decodebin ! audioconvert ! audioresample ! kaldinnet2onlinedecoder use-threaded-decoder=true model=final.mdl fst=HCLG.fst word-syms=words.txt feature-type=mfcc mfcc-config=conf/mfcc.conf ivector-extraction-config=conf/ivector_extractor.fixed.conf max-active=7000 beam=11.0 lattice-beam=5.0 do-endpointing=true endpoint-silence-phones="1:2:3:4:5:6:7:8:9:10" chunk-length-in-secs=0.2 ! filesink location=/dev/stdout buffer-mode=2

I don't get the messages that we can ignore and I get that std::system_error.  Any help would be appreciated.

**Comment by lucgeo** [comment]
Hi,

I have the same issue, if I set the "use-threaded-decoder" as true, it throws the following error message: "terminate called after throwing an instance of 'std::system_error'  what():  Invalid argument". If I set it as false, then everything works, but on a single thread. I also noticed in last commit there is no "-lkaldi-thread" flag in Makefile.

**Comment by alumae** [comment]
I could reproduce this. I am pretty sure that this is a bug in Kaldi's online-nnet2-decoding-threaded.cc. I'll see if I can fix this.

**Comment by alumae** [comment]
I fixed this in Kaldi, see https://github.com/kaldi-asr/kaldi/pull/1725. You need to update Kaldi, and recompile Kaldi and this plugin.
