### ISSUE TITLE
getting different recognition result on exact same inputs

### ISSUE THREAD

**Issue by yifan** [alumae/gst-kaldi-nnet2-online#66]
Hi guys,

I am having strange behaviour with recognition right now. I am sending the audio to server with client.py, and I am getting slightly different result every time I test. AFAIK, the decoding is deterministic, I am not sure what's going on. I checked the saved audios and they are identical.

**Comment by alumae** [comment]
Decoding is not deterministic due to dithering when computing audio features. It's OK for the results to be slightly different.
