### ISSUE TITLE
broken with latest kaldi version

### ISSUE THREAD

**Issue by calderma** [alumae/gst-kaldi-nnet2-online#72]
The latest version of Kaldi (5.5) gets rid of the file context-fst-inl.h in the kaldi-trunk/src/fstext directory which breaks the install, or at least it did for me. If you include that file in your Kaldi install from version 5.4, the Makefile works however.

**Comment by alumae** [comment]
I cannot reproduce this problem. I did `git pull` on Kaldi, made a clean compile, and also made a clean compile on gst-kaldi-nnet2-online, and it compiles successfully.

Maybe (but probably not) it's related to the fact that latest Kaldi depends on openfst 1.6.7? I recompiled Kaldi's openfst (under its tools dir) and updated the tools/openfst symlink to point to openfst-1.6.7

**Comment by calderma** [comment]
Hmm alright. They made a lot of changes to the lattice-faster-online-decoder framework so perhaps it's something to do with my setup. Closing this.
