### ISSUE TITLE
enhancement to online tcp program

### ISSUE THREAD

**Issue by yondu22** [alumae/gst-kaldi-nnet2-online#84]
Could someone work on using this as 
https://github.com/kaldi-asr/kaldi/blob/master/src/online2bin/online2-tcp-nnet3-decode-faster.cc
the base for 

instead of 
https://github.com/kaldi-asr/kaldi/blob/master/src/online2bin/online2-wav-nnet2-latgen-faster.cc

This one allows for the language model to be shared across workers

**Comment by alumae** [comment]
Using another code as a base won't solve this. 
The problem is that different GStreamer instances are executed in different processes and it's very difficult to share data between them.
