### ISSUE TITLE
make Error

### ISSUE THREAD

**Issue by mrlonely001** [alumae/gst-kaldi-nnet2-online#92]
gstkaldinnet2onlinedecoder.cc:1368:62: error: no matching function for call to 'kaldi::SingleUtteranceNnet2DecoderThreaded::SingleUtteranceNnet2DecoderThreaded(kaldi::OnlineNnet2DecodingThreadedConfig&, kaldi::TransitionModel&, kaldi::nnet2::AmNnet&, fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >&, kaldi::OnlineNnet2FeaturePipelineInfo&, kaldi::OnlineIvectorExtractorAdaptationState&, kaldi::OnlineCmvnState&)'
                                         *(filter->cmvn_state));

**Comment by naxingyu** [comment]
Update Kaldi to latest commit and re-make.

**Comment by mrlonely001** [comment]
> Update Kaldi to latest commit and re-make.

Thanks , I make it   https://github.com/mrlonely001/docker-kaldi-gstreamer-server-for-chinese-asr
